### PR TITLE
Enable browser autorefresh to speed UI development

### PR DESCRIPTION
**Pull request by richdouglasevans**
Yo!

This is kinda a pull request maybe: you can merge it if you like but I'm really just sharing. You likely know a better way of doing this: share plox.

This adds automatic refresh of the browser when doing UI changes and speeds up development when you're hacking HAML files. I've got dual monitors at home so I have one monitor displaying the Desperado page I'm designing and the other is RubyMine and the HAML source code. When I save changes to the HAML source the page on the other monitor automatically refreshes to reflect my changes. This means I can stay inside my IDE and don't ever have to TAB out and F5.

To enable this:

* switch to this branch.
* `bundle` to install the [Guard](https://github.com/guard/guard) gem and the LiveReload plugin
* `bundle exec guard` to launch Guard. I do this in a small [tmux](https://tmux.github.io/) pane.
* Install the [LiveReload](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en) extension in Chrome.
* Open [localhost:3000](http://localhost:3000) in Chrome.
* Click the wee `LiveReload` button next to the address bar in Chrome.
* Hack away on the HAML; as you save the page will be refreshed and reflect your edits.

:dollar: :tada:  :smiley: :fire:

### CODE REVIEW

**Comment by muyjohno** [comment]
Cool. I may never use it, but sounds useful. One request: could you add it to a separate `group :development` block in the Gemfile?

With regards to better ways of doing this, I don't really know. I've used Grunt in the past to watch and auto-compile SASS for a static project I was working on. Rails does compilation here, so that doesn't seem like a nice option here. This looks good though. There's a gem for everything.

**Comment by richdouglasevans** [comment]
> Could you add it to a separate group :development block in the Gemfile?

Done. I had a read around to find out _why_ and these blog posts were useful. (These links are mainly for my reference since you already know why.)

* [The How and Why of Bundler Groups](http://yehudakatz.com/2010/05/09/the-how-and-why-of-bundler-groups/)
* [Gemfile Best Practices & Discourse](http://mcdowall.info/posts/gemfile-best-practices-and-discourse/)

**Comment by richdouglasevans** [comment]
On a vaguely related note, Raganwald's [collected adventures in Combinatory Logic and Ruby Meta-Programming](https://leanpub.com/combinators) is free at the moment.

It's well worth a read and kicks off with one of [your fave Ruby methods](http://ruby-doc.org/core-2.2.3/Object.html#method-i-tap) :smile_cat:

**Comment by richdouglasevans** [comment]
> I may never use it, but sounds useful.

Johno, once you get a taste you won't go back. I'll even offer to play nothing but Jinteki Biotech for the whole summer if you give it a go and decide it's not for you.

You can't say fairer than that. :smile:

**Pull request merged**
